apiVersion: v1
kind: Service
metadata:
  name: rapp-catalog
spec:
  selector:
    app: rapp-catalog
  ports:
    - name: http
      port: 9196
      targetPort: 9196
    - name: grpc
      port: 9096
      targetPort: 9096
  type: ClusterIP  # Change to NodePort or LoadBalancer if external access is needed
